CREATE TABLE dbo.BoMon (
    MaBM   VARCHAR(50)  NOT NULL,
    tenBM  VARCHAR(50)  NULL,
    maKhoa VARCHAR(10)  NULL, 
    CONSTRAINT PK_BoMon PRIMARY KEY CLUSTERED (MaBM)
);
GO
ALTER TABLE dbo.BoMon  
ADD CONSTRAINT FK_BoMon_Khoa FOREIGN KEY (maKhoa)  
REFERENCES dbo.Khoa (maKhoa);
GO
IF OBJECT_ID('dbo.BoMon', 'U') IS NOT NULL  
    DROP TABLE dbo.BoMon;  
GO  IF OBJECT_ID('dbo.DKMH', 'U') IS NOT NULL
    DROP TABLE dbo.DKMH;
GO

IF OBJECT_ID('dbo.SinhVien', 'U') IS NOT NULL
    DROP TABLE dbo.SinhVien;
GO

CREATE TABLE dbo.SinhVien (
    masv VARCHAR(50) NOT NULL PRIMARY KEY,
    hoTen NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE dbo.DKMH (
    maLopHP VARCHAR(50) NOT NULL,
    maSV VARCHAR(50) NOT NULL,
    DiemTP FLOAT NULL,
    DiemThi FLOAT NULL,
    PhanTramThi FLOAT NULL,
    CONSTRAINT PK_DKMH PRIMARY KEY CLUSTERED (maLopHP, maSV)
);
GO

ALTER TABLE dbo.DKMH ALTER COLUMN maSV VARCHAR(50) NOT NULL;
ALTER TABLE dbo.SinhVien ALTER COLUMN masv VARCHAR(50) NOT NULL;
GO

ALTER TABLE dbo.DKMH 
ADD CONSTRAINT FK_DKMH_SinhVien 
FOREIGN KEY (maSV) REFERENCES dbo.SinhVien(masv);
GO
IF OBJECT_ID('dbo.DKMH', 'U') IS NOT NULL
    DROP TABLE dbo.DKMH;
GO

IF OBJECT_ID('dbo.SinhVien', 'U') IS NOT NULL
    DROP TABLE dbo.SinhVien;
GO

CREATE TABLE dbo.SinhVien (
    masv VARCHAR(50) NOT NULL PRIMARY KEY,
    hoTen NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE dbo.DKMH (
    maLopHP VARCHAR(50) NOT NULL,
    maSV VARCHAR(50) NOT NULL,
    DiemTP FLOAT NULL,
    DiemThi FLOAT NULL,
    PhanTramThi FLOAT NULL,
    CONSTRAINT PK_DKMH PRIMARY KEY CLUSTERED (maLopHP, maSV)
);
GO

ALTER TABLE dbo.DKMH ALTER COLUMN maSV VARCHAR(50) NOT NULL;
ALTER TABLE dbo.SinhVien ALTER COLUMN masv VARCHAR(50) NOT NULL;
GO

ALTER TABLE dbo.DKMH 
ADD CONSTRAINT FK_DKMH_SinhVien 
FOREIGN KEY (maSV) REFERENCES dbo.SinhVien(masv);
GO
﻿CREATE TABLE dbo.GVCN (
    maLop VARCHAR(10) NOT NULL,  
    maGV VARCHAR(50) NOT NULL,  
    HK INT NOT NULL,
    CONSTRAINT PK_GVCN PRIMARY KEY CLUSTERED (maLop, maGV, HK)
);
GO
ALTER TABLE dbo.GVCN 
ADD CONSTRAINT FK_GVCN_Lop 
FOREIGN KEY (maLop) 
REFERENCES dbo.Lop(maLop);
GO

ALTER TABLE dbo.GVCN 
ADD CONSTRAINT FK_GVCN_GiaoVien 
FOREIGN KEY (maGV) 
REFERENCES dbo.GiaoVien(maGV);
GO
IF OBJECT_ID('dbo.GVCN', 'U') IS NOT NULL
    DROP TABLE dbo.GVCN;
GO

CREATE TABLE [dbo].[GiaoVien](
	[magv] [varchar](50) NOT NULL,
	[hoten] [nvarchar](50) NULL,
	[NgaySinh] [date] NULL,
	[maBM] [varchar](50) NULL,
 CONSTRAINT [PK_GiaoVien] PRIMARY KEY CLUSTERED 
(
	[magv] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Khoa](
	[maKhoa] [varchar](50) NOT NULL,
	[tenKhoa] [nvarchar](50) NULL,
 CONSTRAINT [PK_Khoa] PRIMARY KEY CLUSTERED 
(
	[maKhoa] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Lop](
	[maLop] [varchar](20) NOT NULL,
	[tenLop] [nvarchar](50) NULL,
 CONSTRAINT [PK_Lop] PRIMARY KEY CLUSTERED 
(
	[maLop] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LopHP](
	[maLopHP] [varchar](50) NOT NULL,
	[TenLopHP] [nvarchar](50) NULL,
	[HK] [int] NULL,
	[maMon] [varchar](50) NULL,
	[maGV] [varchar](50) NULL,
 CONSTRAINT [PK_LopHP] PRIMARY KEY CLUSTERED 
(
	[maLopHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_GiaoVien] FOREIGN KEY([maGV])
REFERENCES [dbo].[GiaoVien] ([magv])
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_GiaoVien]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_LopHP] FOREIGN KEY([maLopHP])
REFERENCES [dbo].[LopHP] ([maLopHP])
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_LopHP]
GO
IF OBJECT_ID('dbo.LopHP', 'U') IS NOT NULL
    DROP TABLE dbo.LopHP;
GO


CREATE TABLE dbo.LopSV (
    maLop VARCHAR(10) NOT NULL,  
    maSV VARCHAR(12) NOT NULL,  
    ChucVu NVARCHAR(50) NULL,
    CONSTRAINT PK_LopSV PRIMARY KEY CLUSTERED (maLop, maSV)
);
GO

-- Thêm khóa ngoại FK_LopSV_Lop
ALTER TABLE dbo.LopSV 
ADD CONSTRAINT FK_LopSV_Lop 
FOREIGN KEY (maLop) 
REFERENCES dbo.Lop(maLop);
GO
IF OBJECT_ID('dbo.LopSV', 'U') IS NOT NULL
    DROP TABLE dbo.LopSV;
GO


CREATE TABLE [dbo].[MonHoc](
	[mamon] [varchar](50) NOT NULL,
	[Tenmon] [nvarchar](50) NULL,
	[STC] [int] NULL,
 CONSTRAINT [PK_MonHoc] PRIMARY KEY CLUSTERED 
(
	[mamon] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[GiaoVien](
    [magv] VARCHAR(50) NOT NULL,  
    [hoten] NVARCHAR(50) NULL,
    [NgaySinh] DATE NULL,
    [MaBM] VARCHAR(50) NULL, 
    CONSTRAINT [PK_GiaoVien] PRIMARY KEY CLUSTERED ([magv] ASC)
);
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BoMon')
BEGIN
    ALTER TABLE [dbo].[GiaoVien]
    ADD CONSTRAINT [FK_GiaoVien_BoMon] 
    FOREIGN KEY ([MaBM]) REFERENCES [dbo].[BoMon] ([MaBM]);
END
GO

